export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_APP_LOADING = 'SET_APP_LOADING'
export const SET_DYNAMIC_STATUS = 'SET_DYNAMIC_STATUS'
export const SET_ERROR = 'SET_ERROR'
// export const SET_CURRENT_USER = 'SET_CURRENT_USER'
//
export const SET_STUDENTS = 'SET_STUDENTS'
export const CREATE_STUDENTS = 'CREATE_STUDENTS'
export const SET_STUDENTS_LOADING = 'SET_STUDENTS_LOADING'
// export const CREATE_STUDENTS = 'CREATE_STUDENTS'

